const { Client } = require('@elastic/elasticsearch');
const { createAWSConnection } = require('@acuris/aws-es-connection');

/** This is helper/lib class to return AWS ES client and ES configuration required */

class AWSESLib {
  /**
   * Assign all ENV variable to `this`, to be used in member functions
   * Also will initialise memeber varaibles
   * @param {Object} awsGetCredentials
   * awsGetCredentials need to generated by awsGetCredentials from '@acuris/aws-es-connection'
   */
  constructor(awsGetCredentials) {
    Object.assign(this, process.env);

    this.client = null;
    this.awsCredentials = awsGetCredentials;
  }

  /** Creates ES client */
  createESClient() {
    const esClientConfig = {
      node: this.AWS_ELASTIC_SEARCH,
      ...(this.NODE_ENV !== 'local' && { Connection: createAWSConnection(this.awsCredentials) }),
      requestTimeout: 900000,
    };

    this.client = new Client(esClientConfig);
  }
}

module.exports = new AWSESLib();
